version: '1'
services:
  nodejs-app:
    image: node-express-ec2:1
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db
    restart: always
    container_name: compose-node

  mysql-db:
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: node-express-ec2
      MYSQL_DATABASE: node-express-database
      MYSQL_USER: tsai
      MYSQL_PASSWORD: node-express-ec2
    command: --bind-address=0.0.0.0
    ports:
      - "3306:3306"
    restart: always
    container_name: compose-mysql